
name: todo-clean

services:
  api:
    container_name: todo-clean
    image: todo-clean:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - my_networks
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=YourStrong!Passw0rd
      - POSTGRES_DB=TodoClean 
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/data/db
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_networks

volumes:
  postgres-data:

networks:
  my_networks:
    driver: bridge
